#!/bin/bash
ip=$(ip a | grep -Po "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,2}" | grep -v "^127\." | grep -v "^255\." | grep -v "255$" | grep -v "\.0$")
gateway=$(ip route | awk '{print $3}' | grep -P "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}")
interfaces=$(ip a | grep -P "^\d{1}: " | sed "s/[1-9]: //g" | awk '{print $1}' | sed "s/://g")
netmask=$(echo $ip | grep -Po "\/\d{1,2}")

echo -e "\n[#] Relevant ip address information:"
echo -e "  Current ip:\n>> $ip \n  Current gateway:\n>> $gateway$netmask "
echo -e "\n[#] Interfaces:"

num=1
for i in $(ip a | grep -P "^\d{1}: " | sed "s/[1-9]: //g" | awk '{print $1}' | sed "s/://g"); do
   echo -e ">>  $num: $i"
   ((num++))
done


