#!/bin/bash

#colors
red="\e[91m"
yellow="\e[33m"
end="\e[0m"
green="\e[32m"

#vars
ip=$(ip a | grep -Po "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,2}" | grep -v "^127\." | grep -v "^255\." | grep -v "255$" | grep -v "\.0$")
gateway=$(ip route | awk '{print $3}' | grep -P "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}")
interfaces=$(ip a | grep -P "^\d{1}: " | sed "s/[1-9]: //g" | awk '{print $1}' | sed "s/://g")
netmask=$(echo $ip | grep -Po "\/\d{1,2}")

#copy interface
copynum=1
if [[ $1 == "-ci" && $2 =~ [0-9] ]]; then
   for iface in $interfaces; do
      interface[$copynum]=$iface
      echo ${interface[$2]} | tr -d "\n" | xclip -sel clip
      ((copynum++))
   done
   echo -e "  ${green}[${red}#${green}] ${red}${interface[$2]}${green} has been copied to clipboard ${end}"
   exit 0
fi

#base script
echo -e "${yellow}[#] Relevant ip address information:${end}"
echo -e "${green}   Current ip:${end} \n${red}>>${end} $ip \n  ${green} Current gateway:${end}\n${red}>>${end} $gateway$netmask "
echo -e "${yellow}\n[#] Interfaces:${end}"

num=1
for i in $(ip a | grep -P "^\d{1}: " | sed "s/[1-9]: //g" | awk '{print $1}' | sed "s/://g"); do
   mac=$(ip a | grep -oG '..:..:..:..:..:..' | grep -v "ff:ff:ff:ff:ff:ff" | sort -u | xargs | cut -d " " -f $num) 
   echo -e "$green   $num: $i: $end"
   echo -e "$red>> $end$mac"
   ((num++))
done

