#!/bin/bash
#colors
red="\e[91m"
yellow="\e[33m"
end="\e[0m"
green="\e[32m"
blue="\e[34m"

#vars
ip=$(ip a | grep -Po "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,2}" | grep -v "^127\." | grep -v "^255\." | grep -v "255$" | grep -v "\.0$" | head -n 1)
vpnchecker=$(ip a | grep "tun0")
vpnip=$(ip a | grep -n3 "tun0" | tail -n +4 | grep -oE "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}/[0-9]{1,2}")
gateway=$(ip route | awk '{print $3}' | grep -P "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}" | head -n 1)
vpngateway=$(ip route | grep "tun0" | grep "via" | grep -E "/[0-9]{1,2}" | sed "s/[0-9]\{1,3\}.[0-9]\{1,3\}.[0-9]\{1,3\}.[0-9]\{1,3\}\/[0-9]\{1,2\}//g" | grep -oG "[0-9]\{1,3\}.[0-9]\{1,3\}.[0-9]\{1,3\}.[0-9]\{1,3\}" | sort -u)
interfaces=$(ip a | grep -P "^\d+: " | awk '{print $2}' | sed "s/://g" | sed "s/<[A-Z,_]+>//")
netmask=$(echo $ip | grep -Po "\/\d{1,2}")

#copy interface
copynum=1
if [[ $1 == "-ci" && $2 =~ [0-9] ]]; then
   for iface in $interfaces; do
      interface[$copynum]=$iface
      echo ${interface[$2]} | tr -d "\n" | xclip -sel clip
      ((copynum++))
   done
   echo -e "  ${green}[${red}#${green}] ${red}${interface[$2]}${green} has been copied to clipboard ${end}"
   exit 0
fi

#base script
if [[ $1 == "-nat" || -z "$vpnchecker" ]]; then
   echo -e "${yellow}[#] Relevant ip address information:${end}"
   echo -e "${green}   Current ip:${end} \n${red}>>${end} $ip \n  ${green} Current gateway:${end}\n${red}>>${end} $gateway$netmask "
else 
   netmask=$(echo $vpnip | grep -Po "\/\d{1,2}")
   echo -e "${yellow}[#] Virtual private ip address:${end}"
   echo -e "${green}   Current ip:${end} \n${red}>>${end} $vpnip  $blue[VPN]$end \n  ${green} Current gateway:${end}\n${red}>>${end} $vpngateway$netmask"
fi
echo -e "${yellow}\n[#] Interfaces:${end}"

num=1
for i in $interfaces; do
   mac=$(ip a | grep -oG '..:..:..:..:..:..' | grep -v "ff:ff:ff:ff:ff:ff" | sort -u | xargs | cut -d " " -f $num) 
   echo -e "$green   $num: $i: $end"
   if [ -z "$mac" ];then 
      mac="VPN_Service"
   fi
   echo -e "$red>> $end$mac"
   ((num++))
done

